name: Chaltel College
markdown: redcarpet
safe: true
lsi: false
pygments: true
permalink: pretty
#baseurl: /chaltel-contenidos
baseurl: ''
exclude: ['sass','Gem*','Guard*','*.rb','.sass-cache','.git']
